plugins {
    id "java-library"
}

base {
    archivesName = "seeu-common-1.21.11"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(project.java_version as int)
    }

    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = project.java_version as int
}

dependencies {
    compileOnly "io.netty:netty-buffer:${project.netty_version}"
    testImplementation "io.netty:netty-buffer:${project.netty_version}"
    testImplementation platform("org.junit:junit-bom:5.12.2")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

tasks.named("test") {
    useJUnitPlatform()
}
